import type { Metadata } from 'next'
import { Inter_Tight, Unbounded } from 'next/font/google'
import './globals.css'
import { Nav } from '@/components/Nav/Nav'

const interTight = Inter_Tight({
  weight: ['400', '500', '600'],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-inter-tight',
  display: 'swap',
})

const unbounded = Unbounded({
  weight: ['400', '500', '600'],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-unbounded',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={`${interTight.variable} ${unbounded.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
